-- INSERÇÃO DE DADOS PADRÃO


INSERT INTO grupo_usuario(ID, DESCRICAO, DATA_CRIACAO, DATA_ALTERACAO, FK_ID_USUARIO_ALTERACAO, DATA_EXCLUSAO, FK_ID_USUARIO_EXCLUSAO) 
  VALUES(DEFAULT, 'Administrador', CURRENT_DATE, NULL, NULL, NULL, NULL);

INSERT INTO usuario(ID, LOGIN, SENHA, ATIVO, FK_GRUPO_USUARIO_ID, DATA_CRIACAO, DATA_EXPIRACAO, DATA_ALTERACAO, FK_ID_USUARIO_ALTERACAO, DATA_EXCLUSAO, FK_ID_USUARIO_EXCLUSAO) 
  VALUES(DEFAULT, 'wesley', '123', TRUE, 1, CURRENT_DATE, CURRENT_DATE + INTERVAL '1 YEAR', NULL, NULL, NULL, NULL),
        (DEFAULT, 'marco', '123', TRUE, 1, CURRENT_DATE, CURRENT_DATE + INTERVAL '1 YEAR', NULL, NULL, NULL, NULL);

INSERT INTO menu_painel(ID, TITULO, ORDEM) 
  VALUES(DEFAULT, 'cadastros', 1);

INSERT INTO menu_item(ID, TITULO, IMAGEM, CLASSE_CONTROLLER, ORDEM, FK_ID_MENU_PAINEL) 
  VALUES(DEFAULT, 'usuario', 'user_16', 'Usuario', 1, 1),
        (DEFAULT, 'grupoUsuario', 'users_16', 'GrupoUsuario', 2, 1),
        (DEFAULT, 'cliente', 'users_16', 'Cliente', 3, 1);
